[2021-05-13 09:16:11,853] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-05-13 09:26:11,855] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-05-13 09:36:11,861] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-05-13 09:36:47,718] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group consumer-00 in Empty state. Created a new member id kafka-python-2.0.2-9edeab2a-1d40-4cea-aa23-08123dc662b7 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:47,719] INFO [GroupCoordinator 0]: Preparing to rebalance group consumer-00 in state PreparingRebalance with old generation 42 (__consumer_offsets-23) (reason: Adding new member kafka-python-2.0.2-9edeab2a-1d40-4cea-aa23-08123dc662b7 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:47,720] INFO [GroupCoordinator 0]: Stabilized group consumer-00 generation 43 (__consumer_offsets-23) (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:47,721] INFO [GroupCoordinator 0]: Assignment received from leader for group consumer-00 for generation 43 (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:47,882] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id kafka-python-2.0.2-9edeab2a-1d40-4cea-aa23-08123dc662b7] in group consumer-00 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:47,882] INFO [GroupCoordinator 0]: Preparing to rebalance group consumer-00 in state PreparingRebalance with old generation 43 (__consumer_offsets-23) (reason: removing member kafka-python-2.0.2-9edeab2a-1d40-4cea-aa23-08123dc662b7 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:47,882] INFO [GroupCoordinator 0]: Group consumer-00 with generation 44 is now empty (__consumer_offsets-23) (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:48,114] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group consumer-00 in Empty state. Created a new member id kafka-python-2.0.2-1a4116dc-5d03-4197-8b20-5efd1d50d80f for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:48,115] INFO [GroupCoordinator 0]: Preparing to rebalance group consumer-00 in state PreparingRebalance with old generation 44 (__consumer_offsets-23) (reason: Adding new member kafka-python-2.0.2-1a4116dc-5d03-4197-8b20-5efd1d50d80f with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:48,116] INFO [GroupCoordinator 0]: Stabilized group consumer-00 generation 45 (__consumer_offsets-23) (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:48,117] INFO [GroupCoordinator 0]: Assignment received from leader for group consumer-00 for generation 45 (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:48,229] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id kafka-python-2.0.2-1a4116dc-5d03-4197-8b20-5efd1d50d80f] in group consumer-00 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:48,229] INFO [GroupCoordinator 0]: Preparing to rebalance group consumer-00 in state PreparingRebalance with old generation 45 (__consumer_offsets-23) (reason: removing member kafka-python-2.0.2-1a4116dc-5d03-4197-8b20-5efd1d50d80f on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:36:48,229] INFO [GroupCoordinator 0]: Group consumer-00 with generation 46 is now empty (__consumer_offsets-23) (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:46:11,871] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-05-13 09:52:29,254] INFO Unable to read additional data from server sessionid 0x10035e4ed540002, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:30,555] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:30,562] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:31,479] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-05-13 09:52:31,489] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2021-05-13 09:52:31,491] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2021-05-13 09:52:32,417] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:32,418] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:32,521] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2021-05-13 09:52:33,857] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:33,857] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:35,615] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:35,617] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:36,789] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:36,789] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:37,277] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-05-13 09:52:38,270] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:38,271] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:39,747] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:39,747] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:40,522] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-console-consumer-56822-1-d9c3fe92-769a-473d-b907-28d45ef1d4e2] in group console-consumer-56822 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:52:40,522] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-56822 in state PreparingRebalance with old generation 5 (__consumer_offsets-44) (reason: removing member consumer-console-consumer-56822-1-d9c3fe92-769a-473d-b907-28d45ef1d4e2 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:52:40,522] INFO [GroupCoordinator 0]: Group console-consumer-56822 with generation 6 is now empty (__consumer_offsets-44) (kafka.coordinator.group.GroupCoordinator)
[2021-05-13 09:52:41,058] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:41,059] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:42,172] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:42,172] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:44,067] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:44,068] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:46,035] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:46,036] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:48,113] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:48,114] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:49,320] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:49,321] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:51,067] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:51,067] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:52,968] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:52,969] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:54,278] INFO Opening socket connection to server localhost/[0:0:0:0:0:0:0:1]:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-05-13 09:52:54,279] INFO Socket error occurred: localhost/[0:0:0:0:0:0:0:1]:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
